engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
        mass_threshold: 25
      - javascript:
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
exclude_paths:
- "app/assets/javascripts/bundle.js"
